name: AfkCommandUI
author: assessed
api: 3.0.0
main: summerville\main
version: 1.0.0
description: Afk Plugin made By AssessedPlate93
commands:
    afk:
      permission: afk.command
      description: Sets Player Afk
permissions:
    afk.command:
      default: true